driver:
  name: terraform

provisioner:
  name: terraform

verifier: # https://www.rubydoc.info/github/newcontext-oss/kitchen-terraform/Kitchen/Verifier/Terraform
  name: terraform
  systems:
    - name: system
      backend: gcp
      shell: true

platforms:
  - name: k8s

suites:
  - name: verify
